config/routes.rb
Rails.application.routes.draw do
  resources :levels

  namespace :api do 
    namespace :v1 do
      resources :levels
      resources :scores
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "levels#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/level.rb
class Level < ApplicationRecord
  has_many :scores
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :level
end

app/controllers/api/v1/levels_controller.rb
class Api::V1::LevelsController < ApplicationController
  before_action :set_level, only: [:show]

  def index
    @levels = Level.all 
    render json: @levels
  end

  def show 
    if @level
      render json: @level
    else
      render json: @level.errors
    end
  end

  private
  def set_level
    @level = Level.find(params[:id])
  end

end

app/controllers/api/v1/scores_controller.rb
class Api::V1::ScoresController < ApplicationController
  before_action :set_score, only: [:show]

  def index
    @scores = Score.all.order("seconds ASC") 
    render json: @scores
  end

  def show 
    if @score
      render json: @score
    else
      render json: @score.errors
    end
  end

  def new
    @score = Score.new
  end

  def create
    @score = Score.new(score_params)

    if @score.save
      render json: @score
    else
      render json: @score.errors
    end
  end

  private
  def set_score
    @score = Score.find(params[:id])
  end

  def score_params
    params.permit(:player, :seconds, :level_id)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_forgery_protection
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController

  def index
    @levels = Level.all
    @scores = Score.all.order("seconds ASC")
  end


end

app/helpers/api/v1/levels_helper.rb
module Api::V1::LevelsHelper
end

app/helpers/api/v1/scores_helper.rb
module Api::V1::ScoresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WheresWaldoApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/levels/_form.html.erb
<%= form_with(model: level) do |form| %>
  <% if level.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(level.errors.count, "error") %> prohibited this level from being saved:</h2>

      <ul>
        <% level.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/levels/_level.html.erb
<div id="<%= dom_id level %>">
  <p>
    <strong>Name:</strong>
    <%= level.name %>
  </p>

</div>

app/views/levels/edit.html.erb
<h1>Editing level</h1>

<%= render "form", level: @level %>

<br>

<div>
  <%= link_to "Show this level", @level %> |
  <%= link_to "Back to levels", levels_path %>
</div>

app/views/levels/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Levels</h1>

<div id="levels">
  <% @levels.each do |level| %>
    <%= render level %>
  <% end %>
</div>
<div id="scores">
  <% @scores.each do |score| %>
    <%= score.player %>
    <%= score.seconds %>
  <% end %>
</div>

app/views/levels/new.html.erb
<h1>New level</h1>

<%= render "form", level: @level %>

<br>

<div>
  <%= link_to "Back to levels", levels_path %>
</div>

app/views/levels/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @level %>

<div>
  <%= link_to "Edit this level", edit_level_path(@level) %> |
  <%= link_to "Back to levels", levels_path %>

  <%= button_to "Destroy this level", @level, method: :delete %>
</div>